version: "3.3"
services:
  backend:
    tty: true # 起動しっぱなし
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/var/www
    networks:
      super-network:
        ipv4_address: 10.10.0.3
    command: python3 app.py

  frontend:
    tty: true # 起動しっぱなし
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "cd react-app && npm start"
    ports:
      - "3000:3000"
    networks:
      super-network:
        ipv4_address: 10.10.0.5

networks:
  super-network:
    external: true