version: "3.3"
services:
  backend:
    tty: true # 起動しっぱなし
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/var/www
    networks:
      super-network:
        ipv4_address: 10.10.0.3
    # command: python app.py

  mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
    env_file:
        ./mysql/.env
    networks:
      super-network:
        ipv4_address: 10.10.0.4
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_connections=1000

  frontend:
    tty: true # 起動しっぱなし
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    # command: sh -c "cd react-sample && yarn start"
    ports:
      - "3000:3000"

networks:
  super-network:
    external: true